name: C/C++ CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install clang-format
        run: sudo apt-get install clang-format

      - name: Run clang-format
        run: |
          # Найти и форматировать файлы .cpp и .h в корневом каталоге и подкаталогах
          find . -name "*.cpp" -exec clang-format -i {} \; || echo "No .cpp files found."
          find . -name "*.h" -exec clang-format -i {} \; || echo "No .h files found."

          # Проверка на форматирование
          if ! git diff --exit-code; then
            echo "Code is not formatted correctly. Please run clang-format."
            echo "You can format your code with: 'clang-format -i <file>'"
            exit 0  # Не завершать с ошибкой
          fi

  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install clang-tidy
        run: sudo apt-get install clang-tidy

      - name: Run clang-tidy
        run: |
          # Найти файлы .cpp и .h и запустить clang-tidy, если они есть
          files=$(find . -name "*.cpp" -o -name "*.h")
          if [ -n "$files" ]; then
            echo "$files" | xargs clang-tidy -- -std=c++17
          else
            echo "No files to lint."
          fi
