name: C/C++ CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install clang-format
        run: sudo apt-get install clang-format

      - name: Run clang-format
        run: |
          clang-format -i **/*.cpp **/*.h
          git diff --exit-code || (echo "Code is not formatted correctly. Please run clang-format." && exit 1)

  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install clang-tidy
        run: sudo apt-get install clang-tidy

      - name: Run clang-tidy
        run: |
          find . -name "*.cpp" -o -name "*.h" | xargs clang-tidy -- -std=c++17
