name: Format and Lint C++ Files

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-format clang-tidy

      - name: Find and format all .cpp and .h files
        run: |
          # Найти все файлы .cpp и .h и отформатировать их с помощью clang-format
          find . -type f \( -name "*.cpp" -o -name "*.h" \) -exec clang-format -i {} \;

      - name: Run clang-tidy lint on all .cpp and .h files
        run: |
          # Найти все файлы .cpp и .h и выполнить линтинг с помощью clang-tidy
          find . -type f \( -name "*.cpp" -o -name "*.h" \) -exec clang-tidy {} -- -std=c++17 \;